# These are supported funding model platforms
github: [Techposts]  # Your GitHub username for GitHub Sponsors
patreon: techposts   # Replace with your actual Patreon username
# open_collective: # Leave commented out if not using
# ko_fi: # Leave commented out if not using
# tidelift: # Leave commented out if not using
# community_bridge: # Leave commented out if not using
# liberapay: # Leave commented out if not using
# issuehunt: # Leave commented out if not using
# lfx_crowdfunding: # Leave commented out if not using
# polar: # Leave commented out if not using
# buy_me_a_coffee: # Leave commented out if not using
# thanks_dev: # Leave commented out if not using
custom: ['https://www.paypal.me/RaviSingh126638']  # Your PayPal link
